apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   namespace: development
   name: dave-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
