apiVersion: apps/v1

kind: Deployment


metadata:

  name: ais-ifm
  namespace: default

  labels:

    app: ais

spec:

  replicas: 3

  selector:

    matchLabels:
      app: ais
      tier: web

  template:

    metadata:

      labels:
       app: ais
       tier: web

    spec:

      containers:

      - name: ais

        image: httpd


